name: Gift'DD Sync Queue

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# System Permissions for Deployment
permissions:
  contents: read
  pages: write
  id-token: write

# THE TRAFFIC CONTROLLER
# We use a fixed group "pages" to ensure the website deployment 
# never overlaps or cancels itself.
concurrency:
  group: "pages"
  cancel-in-progress: false 

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 1. Pull Latest Data
        uses: actions/checkout@v4

      - name: 2. Initialize System Sequence
        run: |
          echo ">> ACCESSING ARCHIVE: ${{ github.sha }}"
          echo ">> STATUS: QUEUE AUTHORIZED."

      - name: 3. Setup Pages Infrastructure
        uses: actions/configure-pages@v4

      - name: 4. Package Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Packages your whole project for the web

      - name: 5. Execute Deployment
        id: deployment
        uses: actions/deploy-pages@v4
